export {AnimateBoard} from './AnimateBoard/AnimateBoard';
export {Partners} from './Partners/Partners';
export {MainPrize} from './MainPrize/MainPrize';
export {FirstScreen} from './FirstScreen/FirstScreen';
export {Rules} from './Rules/Rules';
export {Intro} from './Intro/Intro';
export {ProfileData} from './ProfileData/ProfileData';
export {Guaranteed} from './Guaranteed/Guaranteed';
export {Winners} from './Winners/Winners';
